"""empty message

Revision ID: 4cba34ae5d3f
Revises: 9ca2a0cc1309
Create Date: 2025-09-04 19:33:57.502442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cba34ae5d3f'
down_revision: Union[str, None] = '9ca2a0cc1309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('user_cities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'city')
    )
    op.add_column('newsletter_schedules', sa.Column('schedule_config', sa.JSON(), nullable=False))
    op.drop_column('newsletter_schedules', 'schedule_type')
    op.drop_column('newsletter_schedules', 'cron_expression')
    op.drop_column('newsletter_schedules', 'specific_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_schedules', sa.Column('specific_date', sa.DATETIME(), nullable=True))
    op.add_column('newsletter_schedules', sa.Column('cron_expression', sa.VARCHAR(), nullable=True))
    op.add_column('newsletter_schedules', sa.Column('schedule_type', sa.VARCHAR(), nullable=False))
    op.drop_column('newsletter_schedules', 'schedule_config')
    op.drop_table('user_cities')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
