"""Add admin_timezone to schedules

Revision ID: 9ca2a0cc1309
Revises: de5be64336f8
Create Date: 2025-09-02 10:33:39.356414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca2a0cc1309'
down_revision: Union[str, None] = 'de5be64336f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_schedules', sa.Column('admin_timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletter_schedules', 'admin_timezone')
    # ### end Alembic commands ###
