"""add subscription_types and user_subscription_types tables

Revision ID: ae28585b0485
Revises: 4cba34ae5d3f
Create Date: 2025-09-12 14:33:31.120895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae28585b0485'
down_revision: Union[str, None] = '4cba34ae5d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_subscription_types_id'), 'subscription_types', ['id'], unique=False)
    op.create_table('user_subscription_types',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_type_id'], ['subscription_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'subscription_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscription_types')
    op.drop_index(op.f('ix_subscription_types_id'), table_name='subscription_types')
    op.drop_table('subscription_types')
    # ### end Alembic commands ###
